language: php
php:
  - 5.6
  - 5.5

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

install:
  - composer install
  - ./scripts/test/install test root '' localhost $WP_VERSION

script:
  - phpunit
